export const GET_CURRENCY_LIST = 'GET_CURRENCY_LIST';
export const SET_FIRST_CURRENCY = 'SET_FIRST_CURRENCY';
export const SET_SECOND_CURRENCY = 'SET_SECOND_CURRENCY';
export const CHANGE_AMOUNT = 'CHANGE_AMOUNT';
export const SET_AMOUNT_FIRST_CURRENCY = 'SET_AMOUNT_FIRST_CURRENCY';
export const SET_ERROR= 'SET_ERROR';
export const CHANGE_IS_LOADED = 'CHANGE_IS_LOADED';